--- #AWS
- name: VPC Demo
  hosts: all
  become: yes
  tasks:
    - ec2_vpc_net_facts:
        region: us-east-1
        profile: genpact-us-dev
      register: vpc
    - debug:
        msg: "{{vpc}}"

    - ec2_instance_facts:
        region: ap-south-1
        profile: genpact-ind-prod
        register: ec2
      - debug:
          msg: "{{ec2}}"

    # - ec2_ami:
    #     instance_id: i-xxxxxx
    #     wait: yes
    #     name: newtest
