--- #AWS
- name: VPC Demo
  hosts: all
  become: yes
  tasks:
    - remote_action:
        module: ec2_vpc_net_facts
        region: us-east-1
        profile: genpact-us-dev
        register: VPC
    - debug:
        msg: "{{vpc}}"
